<?php
/**
 * Implements hook_feeds_processor_targets_alter().
 */
function hrworks_import_feeds_processor_targets_alter(&$targets, $type, $bundle) {
  if ($type == 'node' && $bundle == 'hrworks_article') {
    // this is where we fill in the Publish Date stuffs
    $targets['published_at'] = array(
      'name' => t('Published At'),
      'description' => t('When the article was actually published, instead of created'),
      'callback' => 'hrworks_import_set_target',
    );
    // maybe try 'pubdate'?
    // $targets['pubdate'] = array(
    //   'name' => t('Published At'),
    //   'description' => t('When the article was actually published, instead of created'),
    //   'callback' => 'hrworks_import_set_target',
    // );
  }
}


/**
 * Mapping callback.
 */
function hrworks_import_set_target($source, $entity, $target, $value, $mapping) {

  feeds_dbg('test');
  feeds_dbg($value);
  $test = strtotime($value);
  feeds_dbg($test);

  // saves the value to the entity
  $entity->{$target}[$entity->language][0]['value'] = $test;

  // saves the text format? full html/filtered
  if (isset($source->importer->processor->config['input_format'])) {
    $entity->{$target}[$entity->language][0]['format'] =
      $source->importer->processor->config['input_format'];
  }
}
